### ISSUE TITLE
slow framerate 3fps

### ISSUE THREAD

**Issue by wearenocomputer** [sadmb/ofxKinect4Azure#1]
Hi,

I have noticed I can only get 3fps even with an empty project with depth only.
What I have found so far is that creating a transformation is very expensive:
So taking this:

`k4a::transformation transformation(calibration);`

out of the update loop and executing it in setup setup seems to work.

**Comment by sadmb** [comment]
Hi,

Thank you for the feedback.
I've merged the dev branch to the master recently so there might be some problem.
I've only checked with my Mac on BootCamp and it seems it works fine at that time.

Can you try dev branch?
I will check master branch tomorrow and fix if there's something wrong.

**Comment by radamchin** [comment]
Hi, I had same issue, just checked out dev branch and fps more around 18fps.
It also resolved visual problem with the example_pointcloud.

**Comment by sadmb** [comment]
@radamchin 
Thanks for trying this. :)
I have just fixed the slow FPS issue with @wearenocomputer 's solution.
Please re-download it and try again.

Point Cloud is not working proplerly yet.
I will try to fix after this work trip.
Thank you. :)

**Comment by sadmb** [comment]
This is fixed at 2b3b60c7cb64919f593f298b4829f7563d5789db.
